server:
  port: 8888
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password:
  redis:
    host: 120.27.218.132
    port: 6379
    password: qwer123321qwer


