# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password:
  redis:
    host: 120.27.218.132
    port: 6379
    password: qwer123321qwer
      pool:
        # 连接池最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间(毫秒)
        timeout: 0

